<?php

declare(strict_types=1);

namespace WyriHaximus\Broadcast;

use Psr\Container\ContainerInterface;
use Psr\EventDispatcher\ListenerProviderInterface;
use WyriHaximus\Broadcast\Generated\AbstractListenerProvider;

/**
 * This extended AbstractListenerProvider class is generated by wyrihaximus/broadcast and inspired by bmack/kart-composer-plugin
 */
final class ContainerListenerProvider extends AbstractListenerProvider implements ListenerProviderInterface
{
    /** @api */
    public function __construct(private readonly ContainerInterface $container)
    {
    }

    final protected function container(): ContainerInterface
    {
        return $this->container;
    }
}
