<?php

declare(strict_types=1);

namespace WyriHaximus\Broadcast;

use Psr\Container\ContainerInterface;
use Psr\EventDispatcher\ListenerProviderInterface;

use function React\Async\async;
use function React\Async\await;

/**
 * This class is generated by wyrihaximus/broadcast and inspired by bmack/kart-composer-plugin
 */
final readonly class ContainerListenerProvider implements ListenerProviderInterface
{
    /**
     * @api
     * @phpstan-ignore ergebnis.noParameterWithContainerTypeDeclaration
     */
    public function __construct(private ContainerInterface $container)
    {
    }

    /** @return iterable<(callable(object): mixed)> */
    final public function getListenersForEvent(object $event): iterable
    {
        // phpcs:disable
        /** @phpstan-ignore generator.valueType */
        yield from match ($event::class) {
            \WyriHaximus\Broadcast\Dummy\Event::class => [
                                                        /** @phpstan-ignore method.nonObject */
                    fn (\WyriHaximus\Broadcast\Dummy\Event $event): mixed => await(async(fn (\WyriHaximus\Broadcast\Dummy\Event $event) =>                    $this->container->get(\WyriHaximus\Broadcast\Dummy\AsyncListener::class)->handle
                    ($event))($event)),
                                    static fn (\WyriHaximus\Broadcast\Dummy\Event $event) => await(async(static fn (\WyriHaximus\Broadcast\Dummy\Event $event) =>                    \WyriHaximus\Broadcast\Dummy\AsyncListener::handleStatic                    ($event))($event)),
                                                                            ([$this->container->get(\WyriHaximus\Broadcast\Dummy\Listener::class), 'handle']),
                                                                            ([$this->container->get(\WyriHaximus\Broadcast\Dummy\Listener::class), 'handleBoth']),
                                                        '\WyriHaximus\Broadcast\Dummy\Listener::handleBothStaticly'                    ,
                            ],
            \stdClass::class => [
                                                                            ([$this->container->get(\WyriHaximus\Broadcast\Dummy\Listener::class), 'handleBoth']),
                                                        '\WyriHaximus\Broadcast\Dummy\Listener::handleBothStaticly'                    ,
                            ],
            default => [],
        };
        // phpcs:enable
    }
}
